# Generated by Django 2.2.3 on 2019-07-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')])),
                ('parking_spot', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('plate', models.CharField(max_length=10)),
                ('color', models.TextField(max_length=10)),
                ('Vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.VehicleType')),
                ('spot', models.ManyToManyField(through='vehicle.Asign', to='vehicle.Park')),
            ],
        ),
        migrations.AddField(
            model_name='asign',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Park'),
        ),
        migrations.AddField(
            model_name='asign',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
        ),
    ]
