# Generated by Django 2.2.3 on 2019-07-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='floor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=4),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to='vehicle'),
        ),
    ]
