# Generated by Django 2.2.3 on 2019-07-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='subtotal',
        ),
    ]
